name: Build Linux AppImage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Moon
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Check Moon version
        run: |
          moon version --all
          moonrun --version

      - name: Install dependencies
        run: |
          rm -rf package-lock.json
          npm install

    #   - name: Fix rollup optional deps
    #     run: npm i @rollup/rollup-linux-x64-gnu --force

      - name: Build JS (Moon + Vite)
        run: npm run build

      - name: Build AppImage
        run: |
          npx electron-builder --linux AppImage --config electron-builder.json

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: releases/*.AppImage

      - name: Generate Version
        id: version
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Release AppImage
        uses: softprops/action-gh-release@v2
        with:
          files: releases/*.AppImage
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
