name: Build macOS DMG

on:
  push:
    branches:
      - main-tmp-disable
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Moon
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Check Moon version
        run: |
          moon version --all
          moonrun --version

      - name: Install dependencies
        run: npm install

      - name: Build JS (Moon + Vite)
        run: npm run build

      - name: Build DMG
        run: npm run app

      - name: Upload DMG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: releases/*.dmg

      - name: Generate Version
        id: version
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Release DMG
        uses: softprops/action-gh-release@v2
        with:
          files: releases/*.dmg
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
